from openjdk:16

WORKDIR /usr/logging 

COPY ms/LoggingServer.java ms/LoggingServicesAI.java ms/LoggingServices.java ./

# Compile the Java files
RUN javac *.java

# Start RMI registry and LoggerServer
CMD sh -c "rmiregistry & sleep 2 && java LoggingServer"

# COPY ms/mysql-connector-java-5.1.45-bin.jar lib/
# ENV CLASSPATH=.:lib/mysql-connector-java-5.1.45-bin.jar:${CLASSPATH}

# COPY ms/Configuration-tmplt.java ./
# RUN sed "s/<PASSWORD>/${MYSQL_PASSWORD}/g" < Configuration-tmplt.java > Configuration.java
# RUN rm Configuration-tmplt.java

# COPY ms/CreateServices.java ms/CreateServicesAI.java ./
# RUN javac *.java

# CMD java CreateServices