from openjdk:16

WORKDIR /usr/logging 

COPY ms/Configuration-tmplt.java ./
RUN sed "s/<PASSWORD>/${MYSQL_PASSWORD}/g" < Configuration-tmplt.java > Configuration.java
RUN rm Configuration-tmplt.java

COPY ms/LoggingServicesAI.java ms/LoggingServices.java ./

# Compile the Java files
RUN javac *.java

# Start RMI registry and LoggerServer
CMD sh -c "rmiregistry & sleep 2 && java LoggingServices"
